title: Md Mehrab Hossain
logo: assets/img/probfile_pic_2.png
description: Lecturer | Machine Learning Enthusiast | Prospective PhD Candidate
email: hmehrab786@gmail.com
google-scholar: https://scholar.google.com/citations?user=ivNRx64AAAAJ&hl=en
theme: jekyll-theme-minimal
