title: Md Mehrab Hossain
logo: assets/img/my_formal_pic.jpg
description: Machine Learning Enthusiast | Prospective PhD Candidate
email: hmehrab786@gmail.com
google-scholar: https://scholar.google.com/citations?user=ivNRx64AAAAJ&hl=en
theme: jekyll-theme-minimal
