title: Md Mehrab Hossain
logo: assets/img/probfile_pic_2.png
description: Lecturer | Machine Learning Enthusiast | Prospective Masters | PhD Candidate 
1. -**Google-Scholar:**[Link](https://scholar.google.com/citations?user=ivNRx64AAAAJ&hl=en)
email: hmehrab786@gmail.com
google-scholar: https://scholar.google.com/citations?user=ivNRx64AAAAJ&hl=en
theme: jekyll-theme-minimal
